use bdescola;

select * from disciplina;
select * from aluno;

SELECT P.NOME_PROFESSOR, (SELECT COUNT(D.ID_PROFESSOR) FROM DISCIPLINA D WHERE D.ID_PROFESSOR = P.ID_PROFESSOR) AS QUANTIDADE_DISCIPLINA FROM PROFESSOR P GROUP BY P.ID_PROFESSOR;

-- Quantidade de disciplinas que cada aluno cursa
SELECT A.NOME_ALUNO, (SELECT COUNT(D.id_DISCIPLINA) FROM DISCIPLINA D, NOTAS N WHERE N.ID_ALUNO = A.ID_ALUNO AND N.ID_DISCIPLINA = D.ID_DISCIPLINA) AS QUANTIDADE_DISCIPLINA FROM ALUNO A;

-- Aluno que tenham 0 notas

-- COM NOT IN
SELECT A.NOME_ALUNO FROM ALUNO A WHERE A.nome_aluno not in (SELECT A.ID_ALUNO FROM NOTAS);

-- também deu certo tambem
SELECT A.NOME_ALUNO, (SELECT COUNT(N.NOTA) FROM NOTAS N WHERE N.ID_ALUNO = A.ID_ALUNO) 
	AS QUANTIDADE_NOTAS FROM ALUNO A HAVING QUANTIDADE_NOTAS < 1;

-- alunos que cursam < 2 disciplinas
SELECT T.NOME_ALUNO, T.QUANTIDADE_DISCIPLINA  FROM (SELECT A.NOME_ALUNO, (SELECT COUNT(D.id_DISCIPLINA) 
	FROM DISCIPLINA D, NOTAS N WHERE N.ID_ALUNO = A.ID_ALUNO AND N.ID_DISCIPLINA = D.ID_DISCIPLINA) AS QUANTIDADE_DISCIPLINA FROM ALUNO A GROUP BY A.ID_ALUNO) T WHERE T.quantidade_disciplina  < 2 ;
