CREATE DATABASE VENDAS;

USE VENDAS;

CREATE TABLE PRODUTOS(

    ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DECRICAO VARCHAR(30),
    ESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DOUBLE

);
    
   
CREATE TABLE VENDA(
 
    ID_VENDA INT NOT  NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VENDA INT NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT
   
 );
 
 
drop table produtos;
drop table venda;

INSERT INTO PRODUTOS (DECRICAO,ESTOQUE_PRODUTO,PRECO_PRODUTO) VALUE ("cuzcuz",35,4);
INSERT INTO PRODUTOS (DECRICAO,ESTOQUE_PRODUTO,PRECO_PRODUTO) VALUE ("FEijao",40,7);
INSERT INTO PRODUTOS (DECRICAO,ESTOQUE_PRODUTO,PRECO_PRODUTO) VALUE ("Macarrao",30,2);


SELECT * FROM PRODUTOS;
delete from produtos where id_produto = 2;

INSERT INTO venda (numero_venda,id_produto, quantidade) VALUE (10,1,15);

DELIMITER $$

CREATE TRIGGER ATUALIZAR_ESTOQUE AFTER INSERT
ON VENDA
FOR EACH ROW

BEGIN

	UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE
    WHERE ID_PRODUTO = NEW.ID_PRODUTO;

END $$

DELIMITER $$
CREATE TRIGGER ATUALIZAR_ESTOQUE AFTER INSERT ON VENDA
FOR EACH ROW

BEGIN
	UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO - NEW.QUANTIDADE
    WHERE ID_PRODUTO = NEW.ID_PRODUTO;
END $$
DELIMITER ;

------------

DELIMITER $$
CREATE TRIGGER DEVOLUCAO_ESTOQUE AFTER DELETE ON VENDA
FOR EACH ROW

BEGIN
	UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO + OLD.QUANTIDADE
    WHERE ID_PRODUTO = OLD.ID_PRODUTO;
END $$
DELIMITER ;

select * from venda;

